name = "lifekline"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "lifepath-db"
database_id = "c58dcf30-bd97-43b3-9b3b-5a259481506a"
